% This script creates a menu driven application

%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% your information
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all;close all;clc;

% Display a menu and get a choice
choice = menu('Choose an option', 'Exit Program', 'Load Image', ...
    'Display Image', 'Task1 Brighten with Loop', 'Task2 Brighten wo Loop', 'Task3 Invert w Loops', 'Task4 Invert wo Loop',...
    'Task 5 AddRandomNoise wo Loops', 'Task6 Luminance wo Loop', 'Task 7 A red filter', ...
    'Task 8 Binary image', 'Task 9 Mean Filter','Talk 10 Frosty Filter',...
    'Task 11 Scale Nearest', 'Task 12 Scale Bilinear', 'Task13 Swirl Filter',...
    'Task 14 Famous Me');  
% as you develop functions, add buttons for them here
 
% Choice 1 is to exit the program
while choice ~= 1
   switch choice
       case 0
           disp('Error - please choose one of the options.')
           % Display a menu and get a choice
           choice = menu('Choose an option', 'Exit Program', 'Load Image', ...
                        'Display Image', 'Task1 Brighten with Loop', 'Task2 Brighten wo Loop', 'Task3 Invert w Loops', 'Task4 Invert wo Loop',...
                        'Task 5 AddRandomNoise wo Loops', 'Task6 Luminance wo Loop', 'Task 7 A red filter', ...
                        'Task 8 Binary image', 'Task 9 Mean Filter','Talk 10 Frosty Filter',...
                        'Task 11 Scale Nearest', 'Task 12 Scale Bilinear', 'Task13 Swirl Filter',...
                        'Task 14 Famous Me');  
        case 2
           % Load an image
           image_choice = menu('Choose an option', 'Exit Program', 'Load Image', ...
                                'Display Image', 'Task1 Brighten with Loop', 'Task2 Brighten wo Loop', 'Task3 Invert w Loops', 'Task4 Invert wo Loop',...
                                'Task 5 AddRandomNoise wo Loops', 'Task6 Luminance wo Loop', 'Task 7 A red filter', ...
                                'Task 8 Binary image', 'Task 9 Mean Filter','Talk 10 Frosty Filter',...
                                'Task 11 Scale Nearest', 'Task 12 Scale Bilinear', 'Task13 Swirl Filter',...
                                'Task 14 Famous Me');  
           switch image_choice
               case 1
                   filename = 'lena1.jpg';
               case 2
                   filename = 'mandril.jpg';
               case 3
                   filename = 'sully.bmp';
               case 4
                   filename = 'yoda.bmp';
               case 5
                   filename = 'shrek.bmp';
               % fill in cases for all the images you plan to use
           end
           current_img = imread(filename);
%            imshow(current_img)
       case 3
           % Display image
           figure
           imagesc(current_img);
           if size(current_img,3) == 1
               colormap gray
           end
           
       case 4
           % ...
       case 5
           %....
       case 6
           %....
       case 7
           %....
       case 8
           %....
       case 9
           %....
       case 10
           %....
       case 11
           %....
       case 12
           %....
       case 13
           %....
       case 14
           %....
       case 15
           %....
       case 16
           %....
       case 17
           %....
           
       %....
   end
   % Display menu again and get user's choice
   choice = menu('Choose an option', 'Exit Program', 'Load Image', ...
    'Display Image', 'Mean Filter');  % as you develop functions, add buttons for them here
end
